/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpplink_Mouselistener */

#ifndef _Included_cpplink_Mouselistener
#define _Included_cpplink_Mouselistener
#ifdef __cplusplus
extern "C" {
#endif
#undef cpplink_Mouselistener_serialVersionUID
#define cpplink_Mouselistener_serialVersionUID 1i64
/*
 * Class:     cpplink_Mouselistener
 * Method:    mrun
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cpplink_Mouselistener_mrun
  (JNIEnv *, jobject);

/*
 * Class:     cpplink_Mouselistener
 * Method:    mend
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cpplink_Mouselistener_mend
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
